name: Java CI with Gradle v4

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :free:shadowJar :premium:shadowJar

      - name: Upload plugin jar (FREE)
        uses: actions/upload-artifact@v4
        with:
          name: ajQueue-FREE
          path: free/build/libs/ajQueue*.jar
          if-no-files-found: error

      - name: Upload plugin jar (PREMIUM)
        uses: actions/upload-artifact@v4
        with:
          name: ajQueue-PREMIUM
          path: premium/build/libs/ajQueue*.jar
          if-no-files-found: error
